spring.application.name=search-service
server.port=8082

# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

# Kafka
spring.kafka.bootstrap-servers=localhost:9092

# Producer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JacksonJsonSerializer

# Producer properties
spring.kafka.producer.properties.spring.json.type.mapping=found-offer:com.ogidazepam.search_service.model.event.JobOfferEvent

# Consumer
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JacksonJsonDeserializer
spring.kafka.consumer.group-id=searcher-group

# Consumer properties
spring.kafka.consumer.properties.spring.json.trusted.packages=com.ogidazepam.search_service.model.event
spring.kafka.consumer.properties.spring.json.type.mapping=created-task:com.ogidazepam.search_service.model.event.CreatedTaskEvent