spring.application.name=job-api-service
server.port=8081

logging.level.org.springframework.security=DEBUG

# Variables
jwt.secret=${SECRET}
jwt.expiration=604800000

# DB
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.url=jdbc:postgresql://localhost:5432/job-searcher

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.show_sql=true

# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

# Kafka
spring.kafka.bootstrap-servers=localhost:9092

# Producer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JacksonJsonSerializer

# Producer properties
spring.kafka.producer.properties.spring.json.type.mapping=created-task:com.ogidazepam.job_api_service.model.event.CreatedTaskEvent

# Consumer
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JacksonJsonDeserializer
spring.kafka.consumer.group-id=collecting-group

# Consumer properties
spring.kafka.consumer.properties.spring.json.trusted.packages=com.ogidazepam.job_api_service.model
spring.kafka.consumer.properties.spring.json.type.mapping=analyzed-offer:com.ogidazepam.job_api_service.model.event.AnalyzedOfferEvent