spring.application.name=job-api-service
server.port=8081

# Validation
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

# DB
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Producer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JacksonJsonSerializer
spring.kafka.producer.acks=all
spring.kafka.producer.retries=2147483647

# Producer properties
spring.kafka.producer.properties.spring.json.type.mapping=created-task:com.ogidazepam.job_api_service.model.event.CreatedTaskEvent
spring.kafka.producer.properties.enable.idempotence=true

# Consumer
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JacksonJsonDeserializer
spring.kafka.consumer.group-id=collecting-group
spring.kafka.consumer.auto-offset-reset=earliest

# Consumer properties
spring.kafka.consumer.properties.spring.json.trusted.packages=com.ogidazepam.job_api_service.model.*
spring.kafka.consumer.properties.spring.json.type.mapping=analyzed-offer:com.ogidazepam.job_api_service.model.event.AnalyzedOfferEvent

spring.profiles.active=dev