# DB
spring.datasource.url=${DB_URL}

# Redis (Production / Container network)
spring.data.redis.host=${REDIS_HOST:redis}
spring.data.redis.port=${REDIS_PORT:6379}

# Kafka (Production Brokers / Docker network)
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:kafka:29092}

# Logging
logging.level.root=INFO
logging.level.com.ogidazepam.search_service=INFO
logging.level.org.springframework.kafka=WARN
logging.level.org.apache.kafka=WARN
