# Redis (Local)
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}

# Kafka (Local Broker)
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

# Hibernate
spring.jpa.properties.hibernate.show_sql=true

# Logging
logging.level.root=INFO
logging.level.com.ogidazepam.search_service=DEBUG
logging.level.org.springframework.kafka=INFO
